#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# PATH
export XDG_CONFIG_HOME=/home/openfoam/.config
export QT_GRAPHICSSYSTEM=native
. /opt/openfoam5/etc/bashrc

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -f 0/T

#------------------------------------------------------------------------------
