#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# PATH
export XDG_CONFIG_HOME=/home/openfoam/.config
export QT_GRAPHICSSYSTEM=native
. /opt/openfoam5/etc/bashrc

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

runApplication blockMesh
cp 0/T.orig 0/T
runApplication setFields
runApplication $application

#------------------------------------------------------------------------------
